<a href="https://colab.research.google.com/github/aruaru0/pytorch-tests/blob/main/adaptive_pooling_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [29]:
x = torch.tensor([float(i) for i in range(100)]).reshape(1, 10, 10)
x.shape, x

(torch.Size([1, 10, 10]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
          [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
          [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
          [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]]]))

In [30]:
avepool = torch.nn.AdaptiveAvgPool2d((5, 5))
maxpool = torch.nn.AdaptiveMaxPool2d((5, 5))

In [32]:
y = avepool(x)
y.shape, y

(torch.Size([1, 5, 5]),
 tensor([[[ 5.5000,  7.5000,  9.5000, 11.5000, 13.5000],
          [25.5000, 27.5000, 29.5000, 31.5000, 33.5000],
          [45.5000, 47.5000, 49.5000, 51.5000, 53.5000],
          [65.5000, 67.5000, 69.5000, 71.5000, 73.5000],
          [85.5000, 87.5000, 89.5000, 91.5000, 93.5000]]]))

In [33]:
y = maxpool(x)
y.shape, y

(torch.Size([1, 5, 5]),
 tensor([[[11., 13., 15., 17., 19.],
          [31., 33., 35., 37., 39.],
          [51., 53., 55., 57., 59.],
          [71., 73., 75., 77., 79.],
          [91., 93., 95., 97., 99.]]]))

In [35]:
pooling = torch.nn.AdaptiveAvgPool2d((10, 10))
y = pooling(x)
y.shape, y

(torch.Size([1, 10, 10]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
          [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
          [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
          [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
          [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
          [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]]]))

In [36]:
pooling = torch.nn.AdaptiveAvgPool2d((20, 20))
y = pooling(x)
y.shape, y

(torch.Size([1, 20, 20]),
 tensor([[[ 0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
            7.,  7.,  8.,  8.,  9.,  9.],
          [ 0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
            7.,  7.,  8.,  8.,  9.,  9.],
          [10., 10., 11., 11., 12., 12., 13., 13., 14., 14., 15., 15., 16., 16.,
           17., 17., 18., 18., 19., 19.],
          [10., 10., 11., 11., 12., 12., 13., 13., 14., 14., 15., 15., 16., 16.,
           17., 17., 18., 18., 19., 19.],
          [20., 20., 21., 21., 22., 22., 23., 23., 24., 24., 25., 25., 26., 26.,
           27., 27., 28., 28., 29., 29.],
          [20., 20., 21., 21., 22., 22., 23., 23., 24., 24., 25., 25., 26., 26.,
           27., 27., 28., 28., 29., 29.],
          [30., 30., 31., 31., 32., 32., 33., 33., 34., 34., 35., 35., 36., 36.,
           37., 37., 38., 38., 39., 39.],
          [30., 30., 31., 31., 32., 32., 33., 33., 34., 34., 35., 35., 36., 36.,
           37., 37., 38., 38., 3

In [37]:
pooling = torch.nn.AdaptiveAvgPool2d((3, 3))
y = pooling(x)
y.shape, y

(torch.Size([1, 3, 3]),
 tensor([[[16.5000, 19.5000, 22.5000],
          [46.5000, 49.5000, 52.5000],
          [76.5000, 79.5000, 82.5000]]]))

In [40]:
!pip install timm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 32.9 MB/s eta 0:00:00


In [41]:
import timm

In [42]:
model = timm.create_model('resnet18')

In [43]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (drop_block): Identity()
      (act1): ReLU(inplace=True)
      (aa): Identity()
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act2): ReLU(inplace=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, m

In [44]:
from timm.layers import SelectAdaptivePool2d

avg : 平均プーリング

max : 最大プーリング

avgmax:平均プーリングと最大プーリングの合計、0.5 で再スケーリング

catavgmax:特徴次元に沿った平均プーリングと最大プーリングの出力の連結。これにより、フィーチャの寸法が 2 倍になることに注意してください。

In [91]:
pooling = SelectAdaptivePool2d(output_size=1, flatten=torch.nn.Flatten(start_dim=1, end_dim=-1), pool_type="avg")

In [92]:
x = torch.tensor([float(i) for i in range(500)]).reshape(1, 5, 10, 10)

pooling(x)

tensor([[ 49.5000, 149.5000, 249.5000, 349.5000, 449.5000]])

In [84]:
t = torch.tensor([i for i in range(8)]).reshape(2,2,2)
t

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [68]:
torch.flatten(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
torch.flatten(t, start_dim=0, end_dim=-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
import torch
from timm import create_model

# SelectAdaptivePool2d 層の作成
pool = SelectAdaptivePool2d(output_size=1, pool_type="max")

# 入力画像の作成
x = torch.randn(1, 3, 100, 100)

# プーリングの実行
y = pool(x)

# 出力サイズの表示
print(y.size())

torch.Size([1, 3, 1, 1])
