<a href="https://colab.research.google.com/github/aruaru0/pytorch-tests/blob/main/conv1d_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch
from torch import nn

In [7]:
conv1d = nn.Conv1d(1,2,3)

In [8]:
conv1d

Conv1d(1, 2, kernel_size=(3,), stride=(1,))

In [9]:
conv1d.weight

Parameter containing:
tensor([[[ 0.2690, -0.3829,  0.5537]],

        [[ 0.3526, -0.1392,  0.3159]]], requires_grad=True)

In [10]:
conv1d.bias

Parameter containing:
tensor([-0.0382, -0.4261], requires_grad=True)

In [11]:
print("weights", '-'*20)
print(conv1d.weight.shape)
print(conv1d.weight)

print("bias", '-'*20)
print(conv1d.bias.shape)
print(conv1d.bias)

weights --------------------
torch.Size([2, 1, 3])
Parameter containing:
tensor([[[ 0.2690, -0.3829,  0.5537]],

        [[ 0.3526, -0.1392,  0.3159]]], requires_grad=True)
bias --------------------
torch.Size([2])
Parameter containing:
tensor([-0.0382, -0.4261], requires_grad=True)


In [33]:
conv1d.weight = nn.Parameter(torch.tensor([[[1.,1.,1.]],[[-1.,2.,-1.]]]))
conv1d.bias = nn.Parameter(torch.tensor([0., 0.]))
print("weights", '-'*20)
print(conv1d.weight.shape)
print(conv1d.weight)

print("bias", '-'*20)
print(conv1d.bias.shape)
print(conv1d.bias)

weights --------------------
torch.Size([2, 1, 3])
Parameter containing:
tensor([[[ 1.,  1.,  1.]],

        [[-1.,  2., -1.]]], requires_grad=True)
bias --------------------
torch.Size([2])
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [43]:
x = torch.tensor([[[float(i) for i in range (1, 11)]]])
print(x.shape)
print(x)

torch.Size([1, 1, 10])
tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])


In [45]:
y = conv1d(x)
print(y)

tensor([[[ 6.,  9., 12., 15., 18., 21., 24., 27.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]],
       grad_fn=<ConvolutionBackward0>)
