<a href="https://colab.research.google.com/github/aruaru0/pytorch-tests/blob/main/dropout_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import torch
from torch import nn

In [70]:
p = 0.4
d = nn.Dropout(p = p)
x = torch.tensor([1.0]*10)
print(x)
y = d(x)
print(y)
# print(1/(1-p))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.6667, 0.0000, 0.0000, 0.0000, 1.6667, 1.6667, 0.0000, 1.6667, 1.6667,
        0.0000])


In [36]:
sum(y == 0)/len(y)

tensor(0.2000)

In [71]:
for _ in range(10) :
  p = 0.5
  d = nn.Dropout(p = p)
  x = torch.tensor([1.0]*100)
  y = d(x)
  print(sum(y==0))


tensor(48)
tensor(50)
tensor(46)
tensor(51)
tensor(57)
tensor(50)
tensor(53)
tensor(37)
tensor(51)
tensor(41)


In [72]:
p = 0.5
d = nn.Dropout(p = p)
x = torch.tensor([1.0]*10)
d.train()
y = d(x)
print(y)
d.eval()
y = d(x)
print(y)

tensor([0., 0., 2., 2., 0., 2., 2., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [56]:
d.training

True