<a href="https://colab.research.google.com/github/aruaru0/pytorch-tests/blob/main/model_soup_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install timm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 29.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 66.5 MB/s eta 0:00:00


In [2]:
import timm

In [3]:
def copy_params(model1, model2) :
  model1.load_state_dict(model2.state_dict())
  return model1

def sum_model_params(modelA, modelB):
    """ modelA + modelB """
    sdA = modelA.state_dict()
    sdB = modelB.state_dict()
    for key in sdA:
        sdA[key] = (sdA[key] + sdB[key])
    modelA.load_state_dict(sdA)
    return modelA

def multi_model_params(model, a):
    """ a * model """
    sd = model.state_dict()
    for key in sd:
        sd[key] = sd[key] * a
    model.load_state_dict(sd)
    return model

In [4]:
model1 = timm.create_model("resnet18", pretrained=True)
model2 = timm.create_model("resnet18", pretrained=True)

model.safetensors:   0%|          | 0.00/46.8M [00:00<?, ?B/s]

In [5]:
model = sum_model_params(model1, model2)
model = multi_model_params(model, 0.5)
# model.state_dict()

In [8]:
!wget https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/RedCat_8727.jpg/440px-RedCat_8727.jpg

--2023-11-01 01:35:31--  https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/RedCat_8727.jpg/440px-RedCat_8727.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.154.240, 2620:0:861:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.154.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39045 (38K) [image/jpeg]
Saving to: ‘440px-RedCat_8727.jpg’

440px-RedCat_8727.j 100%[===================>]  38.13K  --.-KB/s    in 0.01s   

2023-11-01 01:35:32 (2.85 MB/s) - ‘440px-RedCat_8727.jpg’ saved [39045/39045]



In [9]:
import torch
import torchvision
from PIL import Image



file = "/content/440px-RedCat_8727.jpg"
img = Image.open(file)
input = torchvision.transforms.functional.to_tensor(img)

In [10]:
model.eval()
x = model(input.unsqueeze(0)).detach()

In [11]:
model3 = timm.create_model("resnet18", pretrained=True)
model3.eval()
y = model3(input.unsqueeze(0)).detach()

In [12]:
for i, j in zip(x[0], y[0]) :
  print(i,j)

tensor(-9.3719) tensor(-9.3719)
tensor(-9.2380) tensor(-9.2380)
tensor(-9.4721) tensor(-9.4721)
tensor(-9.3025) tensor(-9.3025)
tensor(-8.1278) tensor(-8.1278)
tensor(-8.1768) tensor(-8.1768)
tensor(-8.7862) tensor(-8.7862)
tensor(-8.8318) tensor(-8.8318)
tensor(-7.2997) tensor(-7.2997)
tensor(-9.2286) tensor(-9.2286)
tensor(-10.0918) tensor(-10.0918)
tensor(-9.9890) tensor(-9.9890)
tensor(-9.2767) tensor(-9.2767)
tensor(-8.8675) tensor(-8.8675)
tensor(-9.8108) tensor(-9.8108)
tensor(-9.0099) tensor(-9.0099)
tensor(-10.2589) tensor(-10.2589)
tensor(-10.0105) tensor(-10.0105)
tensor(-9.1362) tensor(-9.1362)
tensor(-9.9517) tensor(-9.9517)
tensor(-9.2395) tensor(-9.2395)
tensor(-8.3823) tensor(-8.3823)
tensor(-9.3215) tensor(-9.3215)
tensor(-8.4823) tensor(-8.4823)
tensor(-10.1124) tensor(-10.1124)
tensor(-10.1332) tensor(-10.1332)
tensor(-10.5245) tensor(-10.5245)
tensor(-10.1868) tensor(-10.1868)
tensor(-10.4122) tensor(-10.4122)
tensor(-9.4527) tensor(-9.4527)
tensor(-10.5515) tensor(

In [13]:
model1 = timm.create_model("resnet18", pretrained=True)
model2 = timm.create_model("resnet18", pretrained=True)
model3 = timm.create_model("resnet18", pretrained=True)
model4 = timm.create_model("resnet18", pretrained=True)

In [17]:
import copy

models = [model1, model2, model3, model4]
n = len(models)

best = None

for bit in range(1, 1<<n) :
  sel = []
  for i in range(n):
    if (bit>>i)%2 : sel.append(i)
  print(sel)
  model = copy.deepcopy(models[sel[0]])
  for i in range(1, len(sel)) :
    print("add ", sel[i])
    model = sum_model_params(model, models[sel[i]])
  model = multi_model_params(model, len(sel))

  モデルを評価する

  if 評価結果がベストならば　:
     best = model



[0]
[1]
[0, 1]
add  1
[2]
[0, 2]
add  2
[1, 2]
add  2
[0, 1, 2]
add  1
add  2
[3]
[0, 3]
add  3
[1, 3]
add  3
[0, 1, 3]
add  1
add  3
[2, 3]
add  3
[0, 2, 3]
add  2
add  3
[1, 2, 3]
add  2
add  3
[0, 1, 2, 3]
add  1
add  2
add  3


In [23]:
import torch
from torch import nn

In [28]:
input_samples = 32
input_channel = 2
x = torch.rand((input_samples,input_channel))
print(x)

tensor([[0.7393, 0.7103],
        [0.1955, 0.5102],
        [0.9233, 0.2299],
        [0.6489, 0.1678],
        [0.6100, 0.2628],
        [0.4312, 0.6737],
        [0.6468, 0.7555],
        [0.3580, 0.2969],
        [0.3530, 0.1765],
        [0.8987, 0.0702],
        [0.6175, 0.7216],
        [0.0066, 0.0452],
        [0.9841, 0.4782],
        [0.9149, 0.2342],
        [0.2152, 0.3166],
        [0.7439, 0.2375],
        [0.2060, 0.4124],
        [0.3658, 0.3167],
        [0.2130, 0.2546],
        [0.7829, 0.3622],
        [0.0338, 0.3052],
        [0.9881, 0.0938],
        [0.7171, 0.4599],
        [0.1871, 0.5133],
        [0.9776, 0.1292],
        [0.3541, 0.3768],
        [0.6004, 0.8655],
        [0.6294, 0.6045],
        [0.1495, 0.7324],
        [0.2257, 0.3083],
        [0.6929, 0.3413],
        [0.2750, 0.3753]])


In [49]:
x = torch.tensor([[0.7393, 0.7103],
        [0.1955, 0.5102],
        [0.9233, 0.2299],
        [0.6489, 0.1678],
        [0.6100, 0.2628],
        [0.4312, 0.6737],
        [0.6468, 0.7555],
        [0.3580, 0.2969],
        [0.3530, 0.1765],
        [0.8987, 0.0702],
        [0.6175, 0.7216],
        [0.0066, 0.0452],
        [0.9841, 0.4782],
        [0.9149, 0.2342],
        [0.2152, 0.3166],
        [0.7439, 0.2375],
        [0.2060, 0.4124],
        [0.3658, 0.3167],
        [0.2130, 0.2546],
        [0.7829, 0.3622],
        [0.0338, 0.3052],
        [0.9881, 0.0938],
        [0.7171, 0.4599],
        [0.1871, 0.5133],
        [0.9776, 0.1292],
        [0.3541, 0.3768],
        [0.6004, 0.8655],
        [0.6294, 0.6045],
        [0.1495, 0.7324],
        [0.2257, 0.3083],
        [0.6929, 0.3413],
        [0.2750, 0.3753]])

In [50]:
x.shape

torch.Size([32, 2])

In [51]:
batch_norm=nn.BatchNorm1d(input_channel)
batch_norm.train()
# y = batch_norm(x[:16])

BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [52]:
print(batch_norm.running_mean, batch_norm.running_var)

tensor([0., 0.]) tensor([1., 1.])


In [53]:
print(torch.mean(x, 0), torch.var(x, 0))

tensor([0.5214, 0.3856]) tensor([0.0906, 0.0476])


In [54]:
m, v = torch.mean(x, 0), torch.std(x, 0)
(x - m)/v

tensor([[ 0.7237,  1.4889],
        [-1.0826,  0.5714],
        [ 1.3349, -0.7138],
        [ 0.4235, -0.9985],
        [ 0.2942, -0.5630],
        [-0.2997,  1.3211],
        [ 0.4165,  1.6961],
        [-0.5428, -0.4066],
        [-0.5594, -0.9587],
        [ 1.2532, -1.4461],
        [ 0.3192,  1.5407],
        [-1.7100, -1.5607],
        [ 1.5369,  0.4247],
        [ 1.3070, -0.6941],
        [-1.0171, -0.3163],
        [ 0.7390, -0.6790],
        [-1.0477,  0.1230],
        [-0.5169, -0.3158],
        [-1.0244, -0.6006],
        [ 0.8685, -0.1072],
        [-1.6197, -0.3685],
        [ 1.5501, -1.3378],
        [ 0.6500,  0.3408],
        [-1.1105,  0.5856],
        [ 1.5153, -1.1755],
        [-0.5558, -0.0402],
        [ 0.2624,  2.2005],
        [ 0.3587,  1.0038],
        [-1.2354,  1.5902],
        [-0.9823, -0.3543],
        [ 0.5696, -0.2030],
        [-0.8185, -0.0471]])

In [55]:
batch_norm=nn.BatchNorm1d(input_channel)
batch_norm.train()

for i in range(100) :
  y = batch_norm(x)
  print(y[:2], torch.mean(y,0), torch.var(y, 0))
  # print(batch_norm.running_mean, batch_norm.running_var)

tensor([[ 0.7353,  1.5126],
        [-1.0998,  0.5805]], grad_fn=<SliceBackward0>) tensor([-3.2037e-07,  2.9802e-08], grad_fn=<MeanBackward1>) tensor([1.0321, 1.0320], grad_fn=<VarBackward0>)
tensor([[ 0.7353,  1.5126],
        [-1.0998,  0.5805]], grad_fn=<SliceBackward0>) tensor([-3.2037e-07,  2.9802e-08], grad_fn=<MeanBackward1>) tensor([1.0321, 1.0320], grad_fn=<VarBackward0>)
tensor([[ 0.7353,  1.5126],
        [-1.0998,  0.5805]], grad_fn=<SliceBackward0>) tensor([-3.2037e-07,  2.9802e-08], grad_fn=<MeanBackward1>) tensor([1.0321, 1.0320], grad_fn=<VarBackward0>)
tensor([[ 0.7353,  1.5126],
        [-1.0998,  0.5805]], grad_fn=<SliceBackward0>) tensor([-3.2037e-07,  2.9802e-08], grad_fn=<MeanBackward1>) tensor([1.0321, 1.0320], grad_fn=<VarBackward0>)
tensor([[ 0.7353,  1.5126],
        [-1.0998,  0.5805]], grad_fn=<SliceBackward0>) tensor([-3.2037e-07,  2.9802e-08], grad_fn=<MeanBackward1>) tensor([1.0321, 1.0320], grad_fn=<VarBackward0>)
tensor([[ 0.7353,  1.5126],
        [-1.

In [45]:
input_samples = 32
input_features = 2
x = torch.rand((input_samples,input_channel))

print("x:", torch.mean(x, 0), torch.var(x, 0))

batch_norm.eval()
for i in range(10) :
  y = batch_norm(x[16:])
  print(batch_norm.running_mean, batch_norm.running_var, torch.mean(y,0), torch.var(y, 0))

x: tensor([0.5036, 0.3448]) tensor([0.0533, 0.0589])
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 0.0476]) tensor([-0.2178,  0.0130], grad_fn=<MeanBackward1>) tensor([0.4012, 0.8329], grad_fn=<VarBackward0>)
tensor([0.5214, 0.3856]) tensor([0.0907, 

In [59]:
batch_norm=nn.BatchNorm1d(input_channel)
# batch_norm.eval()
y = batch_norm(x[:1])
y

ValueError: ignored