<a href="https://colab.research.google.com/github/aruaru0/pytorch-tests/blob/main/smooth_labeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import torch
from torch.nn import CrossEntropyLoss
from torch.nn.functional import one_hot

In [90]:
gt = torch.tensor([0, 0, 1, 0, 0], dtype=torch.float32)
pred = torch.tensor([0.1, 0.1, 0.8, 0.1, 0.1], dtype=torch.float32)

loss = CrossEntropyLoss()
loss(pred, gt)

tensor(1.0940)

In [107]:
import torch
from torch.nn import CrossEntropyLoss

gt = torch.tensor([0, 0, 1, 0, 0], dtype=torch.float32)
pred = torch.tensor([0.1, 0.1, 0.8, 0.1, 0.1], dtype=torch.float32)
loss = CrossEntropyLoss(label_smoothing=0.1)
print(loss(pred, gt))
# tensor(1.1500)

tensor(1.1500)


In [94]:
e = 0.1
k = 5
gt = torch.tensor([0, 0, 1, 0, 0], dtype=torch.float32)
gt = gt*(1-e) + e/k
print(gt)
pred = torch.tensor([0.1, 0.1, 0.8, 0.1, 0.1], dtype=torch.float32)
print(pred)
print(gt)
loss = CrossEntropyLoss()
loss(pred, gt)

tensor([0.0200, 0.0200, 0.9200, 0.0200, 0.0200])
tensor([0.1000, 0.1000, 0.8000, 0.1000, 0.1000])
tensor([0.0200, 0.0200, 0.9200, 0.0200, 0.0200])


tensor(1.1500)

In [104]:
import torch
e = 0.1
k = 5
gt = torch.tensor([2])
gt = torch.nn.functional.one_hot(gt, num_classes=k) * (1-e) + e/k
print(gt)

tensor([[0.0200, 0.0200, 0.9200, 0.0200, 0.0200]])


In [106]:
import torch

e = 0.1
k = 5
gt = torch.tensor([0, 0, 1, 0, 0], dtype=torch.float32)
gt = gt*(1-e) + e/k
print(gt)

tensor([0.0200, 0.0200, 0.9200, 0.0200, 0.0200])
